### DEPRECATED ###
---
- name: Poll Dynatrace Problems API
  hosts: all

  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ DYNATRACE_HOST }}"
        dt_api_token: "{{ DYNATRACE_API_TOKEN }}"
        delay: 30

  rules:
    # Commands to generate mock disk consumption
    # (linux)    fallocate -l 4G dummy.img
    # (windows)  $file = [System.IO.File]::Create("C:\users\ec2-user\dummylarge.txt"); $file.SetLength(10GB); $file.Close();
    - name: Launch Free Disk Space Remediation
      condition: >-
        event.status == "OPEN" and
        event.title == "Free Disk Space Below 30%"
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // Disk Space
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event['impactedEntities'][0]['name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event['title'] }} [{{ event['impactedEntities'][0]['name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event['problemId'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>Impacted: {{ event['impactLevel'] }}</p> <p>Type: {{ event['severityLevel'] }}</p> <p>
                    <a href="{{ DYNATRACE_HOST | replace('live', 'apps') }}/{{ DYNATRACE_PROBLEM_VIEW }}pid={{ event['problemId'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch OneAgent Remediation
      condition: >-
        event.status == "OPEN" and
        event.title == "OneAgent monitoring unavailable"
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // OneAgent
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event['impactedEntities'][0]['name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event['title'] }} [{{ event['impactedEntities'][0]['name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event['problemId'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>Impacted: {{ event['impactLevel'] }}</p> <p>Type: {{ event['severityLevel'] }}</p> <p>
                    <a href="{{ DYNATRACE_HOST | replace('live', 'apps') }}/{{ DYNATRACE_PROBLEM_VIEW }}pid={{ event['problemId'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch High Memory Usage Remediation
      condition: >-
        event.status == "OPEN" and
        event.title is match("The memory usage has spiked")
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // High Memory Usage
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event['impactedEntities'][0]['name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event['title'] }} [{{ event['impactedEntities'][0]['name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event['problemId'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>Impacted: {{ event['impactLevel'] }}</p> <p>Type: {{ event['severityLevel'] }}</p> <p>
                    <a href="{{ DYNATRACE_HOST | replace('live', 'apps') }}/{{ DYNATRACE_PROBLEM_VIEW }}pid={{ event['problemId'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch Generic Remediation Fact Gathering
      # Crawl, walk, run - hone in on specific problem types using conditions
      condition:
        all:
          - event.status == "OPEN"
      action:
        run_job_template:
          name: EDA // Dynatrace Problems
          organization: Autodotes
