### Preferred method for AAP 2.5+ ###
---
- name: Integrate with DataDog Workflow for Event-Driven Ansible
  hosts: all

  sources:
    # will be replaced by Event Stream
    - name: DataDog Event Source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5010

  rules:
    # Commands to generate mock disk consumption
    # (linux)    fallocate -l 4G dummy.img
    # (windows)  $file = [System.IO.File]::Create("C:\users\ec2-user\dummylarge.txt"); $file.SetLength(10GB); $file.Close();
    - name: Launch Free Disk Space Remediation
      condition: event.payload.alert_title is match("Free Disk Space Below", ignorecase=true)
      throttle:
        once_within: 30 minutes
        group_by_attributes:
          - event.payload['hostname']
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // Disk Space
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event.payload['hostname'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event.payload['alert_title'] }} [{{ event.payload['hostname'] }}]"
              inc_description: "Auto-generated event by Ansible for DataDog alert {{ event.payload['event_link'] }}"
              inc_other:
                comments: >
                  [code] <p>
                    <a href="{{ event.payload['event_link'] }}">
                      View Event Details
                    </a>
                  </p> [/code]

    - name: Launch Demo Job
      condition: true
      action:
        run_job_template:
          name: EDA // No-Op
          organization: Autodotes
          job_args:
            extra_vars:
              _hosts: localhost
