---
- name: Basic webhook for demo purposes
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Demo match condition
      condition: event.payload.content is search(search_term | default('alert'))
      action:
        debug:
          msg: "{{ event.payload.payload }}"

    - name: Catch and Log
      condition: 1 == 1
      action:
        debug:
          msg: "{{ event.payload }}"
