### Preferred method for AAP 2.5+ ###
---
- name: Integrate with Dynatrace Workflow for Event-Driven Ansible
  hosts: all

  sources:
    # will be replaced by Event Stream
    - name: Dynatrace Event Source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5010

  rules:
    # Commands to generate mock disk consumption
    # (linux)    fallocate -l 4G dummy.img
    # (windows)  $file = [System.IO.File]::Create("C:\users\ec2-user\dummylarge.txt"); $file.SetLength(10GB); $file.Close();
    - name: Launch Free Disk Space Remediation
      condition: event.payload.name == "Free Disk Space Below 30%"
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // Disk Space
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event.payload['host_name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event.payload['name'] }} [{{ event.payload['host_name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event.payload['problem_id'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>
                    <a href="{{ DT_PROBLEM_VIEW }}pid={{ event.payload['problem_id'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch OneAgent Remediation
      condition: event.payload.name == "OneAgent monitoring unavailable"
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // OneAgent
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event.payload['host_name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event.payload['name'] }} [{{ event.payload['host_name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event.payload['problem_id'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>
                    <a href="{{ DT_PROBLEM_VIEW }}pid={{ event.payload['problem_id'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch High Memory Usage Remediation
      condition: event.payload.name is match("The memory usage has spiked")
      action:
        run_workflow_template:
          name: EDA // Remediation Workflow // High Memory Usage
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event.payload['host_name'] }}"
              _aws_region: "us-east-2"
              inc_short_description: "{{ event.payload['name'] }} [{{ event.payload['host_name'] }}]"
              inc_description: "Auto-generated event by Ansible for Dynatrace problem {{ event.payload['problem_id'] }}"
              inc_other:
                # problem_view: ui/apps/dynatrace.classic.problems/#problems/problemdetails;gtf=-6h;gf=all;
                comments: >
                  [code] <p>
                    <a href="{{ DT_PROBLEM_VIEW }}pid={{ event.payload['problem_id'] }}">
                      View Problem Details
                    </a>
                  </p> [/code]

    - name: Launch Demo Job
      condition: true
      action:
        run_job_template:
          name: EDA // No-Op
          organization: Autodotes
          job_args:
            extra_vars:
              _hosts: localhost
