---
- name: Basic local webhook for testing
  hosts: all

  sources:
    - zjleblanc.utils.custom_webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Launch Remediation Job
      condition: event.payload.incident.alerts[0].tags is selectattr('value', '==', 'cpu')
      action:
        debug:
          msg: "{{ event.payload.payload }}"

    - name: Catch and Log
      condition: 1 == 1
      action:
        debug:
          msg: "{{ event.payload }}"
