---
- name: Ingest Service Now Requested Items
  hosts: all

  sources:
    # will be replaced by Event Stream
    - name: Service Now Event Source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Provision VM
      condition: event.payload.cat_item == 'a1adfeaf87f46a1064a055383cbb35d9'
      action:
        run_workflow_template:
          name: AWS // Provisioning Workflow
          organization: Autodotes
          job_args:
            extra_vars:
              aws_ec2_names_list: "{{ event.payload['variables']['sn_vm_name'] }}"
              target_platform: "{{ event.payload['variables']['sn_target_platform'] }}"
              aws_region: "{{ event.payload['variables']['sn_aws_region'] }}"

    - name: Decommission VM
      condition: event.payload.cat_item == '85c7c43f873c6a1064a055383cbb35dc'
      action:
        run_workflow_template:
          name: AWS // Decommission Workflow
          organization: Autodotes
          job_args:
            extra_vars:
              aws_ec2_names_list: "{{ event.payload['variables']['sn_vm_name'] }}"

    - name: Catch 'em All
      condition: 1 == 1
      action:
        debug:
          msg: "{{ event.payload }}"