---
- name: Watch for new snow records and alerts
  hosts: localhost

  sources:
    - cloin.eda.snow_records:
        instance: "{{ SN_HOST }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        table: sc_req_item
        interval: 1

    - cloin.eda.snow_records:
        instance: "{{ SN_HOST }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        table: incident
        interval: 1

  rules:
    - name: Launch Demo Job
      condition: event.sys_id is defined
      action:
        run_job_template:
          name: EDA // No-Op
          organization: Autodotes
          job_args:
            extra_vars:
              _hosts: "{{ event.payload._hosts | default('localhost') }}"
